---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kabanero-index
  labels:
    app: kabanero-index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kabanero-index
  template:
    metadata:
      labels:
        app: kabanero-index
      annotations:
        date: "DATE"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: nginx
        image: REGISTRY/NAMESPACE/kabanero-index:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: EXTERNAL_URL
          value: "http://HOST"
---
apiVersion: v1
kind: Service
metadata:
  name: kabanero-index
  labels:
    app: kabanero-index
spec:
  type: ClusterIP
  selector:
    app: kabanero-index
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kabanero-index
spec:
  host: HOST
  to:
    kind: Service
    name: kabanero-index
